/*
 * FractalSandboxAuth
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-07-25T12:16:02Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.fractal.client;

import com.fractal.client.model.ErrorResponse;
import com.fractal.client.model.JWT;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rootOptionsTest() {
        api.rootOptions();

        // TODO: test validations
    }
    
    /**
     * JWT Auth endpoint
     *
     * JWT Auth endpoint
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void rootPostTest() {
        String xApiKey = "SGP2ktEFEs45LY9x5T1WU8hgPOxYQfqy1fgcptfE";
        String xPartnerId = "5111acc7-c9b3-4d2a-9418-16e97b74b1e6";
        JWT response = api.rootPost(xApiKey, xPartnerId);
        
        System.out.println(response.getAccessToken());

        // TODO: test validations
    }
    
}
