/*
 * FractalSandboxBankApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-17T10:22:19Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fractal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BalancesResponseResults
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-25T13:59:29.760Z")
public class BalancesResponseResults {
  @JsonProperty("date")
  private String date = null;

  @JsonProperty("balance-id")
  private String balanceId = null;

  @JsonProperty("companyId")
  private Integer companyId = null;

  @JsonProperty("bankId")
  private Integer bankId = null;

  @JsonProperty("amount")
  private String amount = null;

  @JsonProperty("AccountId")
  private String accountId = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("currencyCode")
  private String currencyCode = null;

  @JsonProperty("status")
  private String status = null;

  public BalancesResponseResults date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @ApiModelProperty(value = "")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public BalancesResponseResults balanceId(String balanceId) {
    this.balanceId = balanceId;
    return this;
  }

   /**
   * Get balanceId
   * @return balanceId
  **/
  @ApiModelProperty(value = "")
  public String getBalanceId() {
    return balanceId;
  }

  public void setBalanceId(String balanceId) {
    this.balanceId = balanceId;
  }

  public BalancesResponseResults companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  @ApiModelProperty(value = "")
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public BalancesResponseResults bankId(Integer bankId) {
    this.bankId = bankId;
    return this;
  }

   /**
   * Get bankId
   * @return bankId
  **/
  @ApiModelProperty(value = "")
  public Integer getBankId() {
    return bankId;
  }

  public void setBankId(Integer bankId) {
    this.bankId = bankId;
  }

  public BalancesResponseResults amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public BalancesResponseResults accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(value = "")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public BalancesResponseResults type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BalancesResponseResults currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public BalancesResponseResults status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalancesResponseResults balancesResponseResults = (BalancesResponseResults) o;
    return Objects.equals(this.date, balancesResponseResults.date) &&
        Objects.equals(this.balanceId, balancesResponseResults.balanceId) &&
        Objects.equals(this.companyId, balancesResponseResults.companyId) &&
        Objects.equals(this.bankId, balancesResponseResults.bankId) &&
        Objects.equals(this.amount, balancesResponseResults.amount) &&
        Objects.equals(this.accountId, balancesResponseResults.accountId) &&
        Objects.equals(this.type, balancesResponseResults.type) &&
        Objects.equals(this.currencyCode, balancesResponseResults.currencyCode) &&
        Objects.equals(this.status, balancesResponseResults.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(date, balanceId, companyId, bankId, amount, accountId, type, currencyCode, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalancesResponseResults {\n");
    
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    balanceId: ").append(toIndentedString(balanceId)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    bankId: ").append(toIndentedString(bankId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

