/*
 * FractalSandboxBankApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-17T10:22:19Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fractal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * BankTransactions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-25T13:59:29.760Z")
public class BankTransactions {
  @JsonProperty("amount")
  private String amount = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("merchant")
  private String merchant = null;

  @JsonProperty("transactionSubCode")
  private String transactionSubCode = null;

  @JsonProperty("transactionCode")
  private String transactionCode = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("transactionId")
  private String transactionId = null;

  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("companyId")
  private Integer companyId = null;

  @JsonProperty("proprietarySubCode")
  private String proprietarySubCode = null;

  @JsonProperty("bookingDate")
  private String bookingDate = null;

  @JsonProperty("proprietaryCode")
  private String proprietaryCode = null;

  @JsonProperty("currencyCode")
  private String currencyCode = null;

  @JsonProperty("status")
  private String status = null;

  public BankTransactions amount(String amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public String getAmount() {
    return amount;
  }

  public void setAmount(String amount) {
    this.amount = amount;
  }

  public BankTransactions description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BankTransactions merchant(String merchant) {
    this.merchant = merchant;
    return this;
  }

   /**
   * Get merchant
   * @return merchant
  **/
  @ApiModelProperty(value = "")
  public String getMerchant() {
    return merchant;
  }

  public void setMerchant(String merchant) {
    this.merchant = merchant;
  }

  public BankTransactions transactionSubCode(String transactionSubCode) {
    this.transactionSubCode = transactionSubCode;
    return this;
  }

   /**
   * Get transactionSubCode
   * @return transactionSubCode
  **/
  @ApiModelProperty(value = "")
  public String getTransactionSubCode() {
    return transactionSubCode;
  }

  public void setTransactionSubCode(String transactionSubCode) {
    this.transactionSubCode = transactionSubCode;
  }

  public BankTransactions transactionCode(String transactionCode) {
    this.transactionCode = transactionCode;
    return this;
  }

   /**
   * Get transactionCode
   * @return transactionCode
  **/
  @ApiModelProperty(value = "")
  public String getTransactionCode() {
    return transactionCode;
  }

  public void setTransactionCode(String transactionCode) {
    this.transactionCode = transactionCode;
  }

  public BankTransactions type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BankTransactions transactionId(String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

   /**
   * Get transactionId
   * @return transactionId
  **/
  @ApiModelProperty(value = "")
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(String transactionId) {
    this.transactionId = transactionId;
  }

  public BankTransactions reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @ApiModelProperty(value = "")
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public BankTransactions companyId(Integer companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Get companyId
   * @return companyId
  **/
  @ApiModelProperty(value = "")
  public Integer getCompanyId() {
    return companyId;
  }

  public void setCompanyId(Integer companyId) {
    this.companyId = companyId;
  }

  public BankTransactions proprietarySubCode(String proprietarySubCode) {
    this.proprietarySubCode = proprietarySubCode;
    return this;
  }

   /**
   * Get proprietarySubCode
   * @return proprietarySubCode
  **/
  @ApiModelProperty(value = "")
  public String getProprietarySubCode() {
    return proprietarySubCode;
  }

  public void setProprietarySubCode(String proprietarySubCode) {
    this.proprietarySubCode = proprietarySubCode;
  }

  public BankTransactions bookingDate(String bookingDate) {
    this.bookingDate = bookingDate;
    return this;
  }

   /**
   * Get bookingDate
   * @return bookingDate
  **/
  @ApiModelProperty(value = "")
  public String getBookingDate() {
    return bookingDate;
  }

  public void setBookingDate(String bookingDate) {
    this.bookingDate = bookingDate;
  }

  public BankTransactions proprietaryCode(String proprietaryCode) {
    this.proprietaryCode = proprietaryCode;
    return this;
  }

   /**
   * Get proprietaryCode
   * @return proprietaryCode
  **/
  @ApiModelProperty(value = "")
  public String getProprietaryCode() {
    return proprietaryCode;
  }

  public void setProprietaryCode(String proprietaryCode) {
    this.proprietaryCode = proprietaryCode;
  }

  public BankTransactions currencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
    return this;
  }

   /**
   * Get currencyCode
   * @return currencyCode
  **/
  @ApiModelProperty(value = "")
  public String getCurrencyCode() {
    return currencyCode;
  }

  public void setCurrencyCode(String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public BankTransactions status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankTransactions bankTransactions = (BankTransactions) o;
    return Objects.equals(this.amount, bankTransactions.amount) &&
        Objects.equals(this.description, bankTransactions.description) &&
        Objects.equals(this.merchant, bankTransactions.merchant) &&
        Objects.equals(this.transactionSubCode, bankTransactions.transactionSubCode) &&
        Objects.equals(this.transactionCode, bankTransactions.transactionCode) &&
        Objects.equals(this.type, bankTransactions.type) &&
        Objects.equals(this.transactionId, bankTransactions.transactionId) &&
        Objects.equals(this.reference, bankTransactions.reference) &&
        Objects.equals(this.companyId, bankTransactions.companyId) &&
        Objects.equals(this.proprietarySubCode, bankTransactions.proprietarySubCode) &&
        Objects.equals(this.bookingDate, bankTransactions.bookingDate) &&
        Objects.equals(this.proprietaryCode, bankTransactions.proprietaryCode) &&
        Objects.equals(this.currencyCode, bankTransactions.currencyCode) &&
        Objects.equals(this.status, bankTransactions.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, description, merchant, transactionSubCode, transactionCode, type, transactionId, reference, companyId, proprietarySubCode, bookingDate, proprietaryCode, currencyCode, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankTransactions {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    transactionSubCode: ").append(toIndentedString(transactionSubCode)).append("\n");
    sb.append("    transactionCode: ").append(toIndentedString(transactionCode)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    proprietarySubCode: ").append(toIndentedString(proprietarySubCode)).append("\n");
    sb.append("    bookingDate: ").append(toIndentedString(bookingDate)).append("\n");
    sb.append("    proprietaryCode: ").append(toIndentedString(proprietaryCode)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

