/*
 * FractalSandboxCompany
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-17T10:28:54Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fractal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fractal.client.model.CompanyRegisteredAddress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Company
 */
@ApiModel(description = "Company")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-25T14:00:22.971Z")
public class Company {
  @JsonProperty("createdAt")
  private String createdAt = null;

  @JsonProperty("yearEndMonth")
  private Integer yearEndMonth = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("registeredAddress")
  private CompanyRegisteredAddress registeredAddress = null;

  @JsonProperty("blocked")
  private Boolean blocked = null;

  @JsonProperty("yearEndDay")
  private Integer yearEndDay = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("industry")
  private String industry = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("id")
  private Integer id = null;

  @JsonProperty("pitch")
  private String pitch = null;

  public Company createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public Company yearEndMonth(Integer yearEndMonth) {
    this.yearEndMonth = yearEndMonth;
    return this;
  }

   /**
   * Get yearEndMonth
   * @return yearEndMonth
  **/
  @ApiModelProperty(value = "")
  public Integer getYearEndMonth() {
    return yearEndMonth;
  }

  public void setYearEndMonth(Integer yearEndMonth) {
    this.yearEndMonth = yearEndMonth;
  }

  public Company website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public Company registeredAddress(CompanyRegisteredAddress registeredAddress) {
    this.registeredAddress = registeredAddress;
    return this;
  }

   /**
   * Get registeredAddress
   * @return registeredAddress
  **/
  @ApiModelProperty(value = "")
  public CompanyRegisteredAddress getRegisteredAddress() {
    return registeredAddress;
  }

  public void setRegisteredAddress(CompanyRegisteredAddress registeredAddress) {
    this.registeredAddress = registeredAddress;
  }

  public Company blocked(Boolean blocked) {
    this.blocked = blocked;
    return this;
  }

   /**
   * Get blocked
   * @return blocked
  **/
  @ApiModelProperty(value = "")
  public Boolean isBlocked() {
    return blocked;
  }

  public void setBlocked(Boolean blocked) {
    this.blocked = blocked;
  }

  public Company yearEndDay(Integer yearEndDay) {
    this.yearEndDay = yearEndDay;
    return this;
  }

   /**
   * Get yearEndDay
   * @return yearEndDay
  **/
  @ApiModelProperty(value = "")
  public Integer getYearEndDay() {
    return yearEndDay;
  }

  public void setYearEndDay(Integer yearEndDay) {
    this.yearEndDay = yearEndDay;
  }

  public Company name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Company industry(String industry) {
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @ApiModelProperty(value = "")
  public String getIndustry() {
    return industry;
  }

  public void setIndustry(String industry) {
    this.industry = industry;
  }

  public Company currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Company id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Company pitch(String pitch) {
    this.pitch = pitch;
    return this;
  }

   /**
   * Get pitch
   * @return pitch
  **/
  @ApiModelProperty(value = "")
  public String getPitch() {
    return pitch;
  }

  public void setPitch(String pitch) {
    this.pitch = pitch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Company company = (Company) o;
    return Objects.equals(this.createdAt, company.createdAt) &&
        Objects.equals(this.yearEndMonth, company.yearEndMonth) &&
        Objects.equals(this.website, company.website) &&
        Objects.equals(this.registeredAddress, company.registeredAddress) &&
        Objects.equals(this.blocked, company.blocked) &&
        Objects.equals(this.yearEndDay, company.yearEndDay) &&
        Objects.equals(this.name, company.name) &&
        Objects.equals(this.industry, company.industry) &&
        Objects.equals(this.currency, company.currency) &&
        Objects.equals(this.id, company.id) &&
        Objects.equals(this.pitch, company.pitch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, yearEndMonth, website, registeredAddress, blocked, yearEndDay, name, industry, currency, id, pitch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Company {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    yearEndMonth: ").append(toIndentedString(yearEndMonth)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    registeredAddress: ").append(toIndentedString(registeredAddress)).append("\n");
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    yearEndDay: ").append(toIndentedString(yearEndDay)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    pitch: ").append(toIndentedString(pitch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

