/*
 * FractalSandboxBankApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-17T10:22:19Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fractal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ConsentsResponseResults
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-25T13:59:29.760Z")
public class ConsentsResponseResults {
  @JsonProperty("expiryDate")
  private String expiryDate = null;

  @JsonProperty("bank_id")
  private Integer bankId = null;

  @JsonProperty("date_authorised")
  private String dateAuthorised = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("consent_id")
  private String consentId = null;

  public ConsentsResponseResults expiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
    return this;
  }

   /**
   * Get expiryDate
   * @return expiryDate
  **/
  @ApiModelProperty(value = "")
  public String getExpiryDate() {
    return expiryDate;
  }

  public void setExpiryDate(String expiryDate) {
    this.expiryDate = expiryDate;
  }

  public ConsentsResponseResults bankId(Integer bankId) {
    this.bankId = bankId;
    return this;
  }

   /**
   * Get bankId
   * @return bankId
  **/
  @ApiModelProperty(value = "")
  public Integer getBankId() {
    return bankId;
  }

  public void setBankId(Integer bankId) {
    this.bankId = bankId;
  }

  public ConsentsResponseResults dateAuthorised(String dateAuthorised) {
    this.dateAuthorised = dateAuthorised;
    return this;
  }

   /**
   * Get dateAuthorised
   * @return dateAuthorised
  **/
  @ApiModelProperty(value = "")
  public String getDateAuthorised() {
    return dateAuthorised;
  }

  public void setDateAuthorised(String dateAuthorised) {
    this.dateAuthorised = dateAuthorised;
  }

  public ConsentsResponseResults type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @ApiModelProperty(value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ConsentsResponseResults consentId(String consentId) {
    this.consentId = consentId;
    return this;
  }

   /**
   * Get consentId
   * @return consentId
  **/
  @ApiModelProperty(value = "")
  public String getConsentId() {
    return consentId;
  }

  public void setConsentId(String consentId) {
    this.consentId = consentId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentsResponseResults consentsResponseResults = (ConsentsResponseResults) o;
    return Objects.equals(this.expiryDate, consentsResponseResults.expiryDate) &&
        Objects.equals(this.bankId, consentsResponseResults.bankId) &&
        Objects.equals(this.dateAuthorised, consentsResponseResults.dateAuthorised) &&
        Objects.equals(this.type, consentsResponseResults.type) &&
        Objects.equals(this.consentId, consentsResponseResults.consentId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiryDate, bankId, dateAuthorised, type, consentId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentsResponseResults {\n");
    
    sb.append("    expiryDate: ").append(toIndentedString(expiryDate)).append("\n");
    sb.append("    bankId: ").append(toIndentedString(bankId)).append("\n");
    sb.append("    dateAuthorised: ").append(toIndentedString(dateAuthorised)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    consentId: ").append(toIndentedString(consentId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

