/*
 * FractalSandboxCompany
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-10-17T10:28:54Z
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.fractal.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Company post body
 */
@ApiModel(description = "Company post body")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-11-25T14:00:22.971Z")
public class CreateCompany {
  @JsonProperty("yEndMonth")
  private Integer yEndMonth = null;

  @JsonProperty("website")
  private String website = null;

  @JsonProperty("address")
  private String address = null;

  @JsonProperty("yEndDay")
  private Integer yEndDay = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("industry")
  private String industry = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("pitch")
  private String pitch = null;

  public CreateCompany yEndMonth(Integer yEndMonth) {
    this.yEndMonth = yEndMonth;
    return this;
  }

   /**
   * Get yEndMonth
   * @return yEndMonth
  **/
  @ApiModelProperty(value = "")
  public Integer getYEndMonth() {
    return yEndMonth;
  }

  public void setYEndMonth(Integer yEndMonth) {
    this.yEndMonth = yEndMonth;
  }

  public CreateCompany website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public CreateCompany address(String address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @ApiModelProperty(value = "")
  public String getAddress() {
    return address;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public CreateCompany yEndDay(Integer yEndDay) {
    this.yEndDay = yEndDay;
    return this;
  }

   /**
   * Get yEndDay
   * @return yEndDay
  **/
  @ApiModelProperty(value = "")
  public Integer getYEndDay() {
    return yEndDay;
  }

  public void setYEndDay(Integer yEndDay) {
    this.yEndDay = yEndDay;
  }

  public CreateCompany name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CreateCompany industry(String industry) {
    this.industry = industry;
    return this;
  }

   /**
   * Get industry
   * @return industry
  **/
  @ApiModelProperty(value = "")
  public String getIndustry() {
    return industry;
  }

  public void setIndustry(String industry) {
    this.industry = industry;
  }

  public CreateCompany currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  @ApiModelProperty(value = "")
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public CreateCompany pitch(String pitch) {
    this.pitch = pitch;
    return this;
  }

   /**
   * Get pitch
   * @return pitch
  **/
  @ApiModelProperty(value = "")
  public String getPitch() {
    return pitch;
  }

  public void setPitch(String pitch) {
    this.pitch = pitch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateCompany createCompany = (CreateCompany) o;
    return Objects.equals(this.yEndMonth, createCompany.yEndMonth) &&
        Objects.equals(this.website, createCompany.website) &&
        Objects.equals(this.address, createCompany.address) &&
        Objects.equals(this.yEndDay, createCompany.yEndDay) &&
        Objects.equals(this.name, createCompany.name) &&
        Objects.equals(this.industry, createCompany.industry) &&
        Objects.equals(this.currency, createCompany.currency) &&
        Objects.equals(this.pitch, createCompany.pitch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(yEndMonth, website, address, yEndDay, name, industry, currency, pitch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateCompany {\n");
    
    sb.append("    yEndMonth: ").append(toIndentedString(yEndMonth)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    yEndDay: ").append(toIndentedString(yEndDay)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    pitch: ").append(toIndentedString(pitch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

